# Generated by Django 5.0.8 on 2024-09-06 20:56

import charidfield.fields
import django.core.validators
import django.db.models.deletion
import ksuid.ksuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsModel',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='awsModel_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('endpoint_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='image_', primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255, validators=[django.core.validators.validate_image_file_extension])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('creation_date_time', models.DateTimeField()),
                ('storage_url', models.URLField()),
                ('observation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.observation')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOperation',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='imageOperation_', primary_key=True, serialize=False, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('in progress', 'In Progress'), ('failure', 'Failure')], max_length=50)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging.image')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging.awsmodel')),
            ],
        ),
    ]
