version: '3.8'

services: 
    postgres:
        image: postgres:16
        # image: postgis/postgis:16-3.4
        restart: unless-stopped
        container_name: postgres_db
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app_db
        ports:
            - 5432:5432
        # volumes:
        #     - postgresdata:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: unless-stopped
        depends_on:
            - postgres
        environment:
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DESIGN: dracula
        ports:
            - 8080:8080
        container_name: adminer

    # nginx:
    #     restart: always
    #     build: ./nginx/
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - web-static:/www/static
    #     links:
    #         - web:web
    #     container_name: nginx

    redis:
        image: redis:7.4.0
        restart: unless-stopped
        ports:
            - "6379:6379"
        container_name: redis
        # volumes:
        #     - redisdata:/data

    # django-app:
    #     image:
    #     container_name: pgc-consortium
    #     expose: 
    #         - "8000"
    #     environment:
    #         - PYTHONDONTWRITEBYTECODE=1
    #         - PYTHONUNBUFFERED=1
    #     volumes:
    #         - djangodata

        
    


        
# volumes:
#     postgresdata:
#     redisdata:
#     djangodata:

