# Generated by Django 5.0.8 on 2024-09-06 20:56

import charidfield.fields
import django.db.models.deletion
import ksuid.ksuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgroProcess',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='agroProcess_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('external_id', models.CharField(max_length=255)),
                ('external_reference', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TraitAttribute',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='traitAttr_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraitEntity',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='traitEntity_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='variable_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255, unique=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('corn', 'Corn'), ('soybean', 'Soybean'), ('pgc grass', 'PGC Grass'), ('pgc clover', 'PGC Clover'), ('weed', 'Weed'), ('soil', 'Soil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarMethod',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='varMethod_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarScale',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='varScale_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SopDocument',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='sop_', primary_key=True, serialize=False, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, null=True)),
                ('doi', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
                ('variable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sop_documents', to='ontology.variable')),
            ],
        ),
        migrations.AddField(
            model_name='variable',
            name='method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.varmethod'),
        ),
        migrations.AddField(
            model_name='variable',
            name='scale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.varscale'),
        ),
        migrations.CreateModel(
            name='VarTrait',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='varTrait_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.traitattribute')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.traitentity')),
            ],
        ),
        migrations.AddField(
            model_name='variable',
            name='trait_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.vartrait'),
        ),
    ]
