# Generated by Django 5.0.8 on 2025-02-03 21:32

import charidfield.fields
import django.db.models.deletion
import ksuid.ksuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable='False', help_text='ksuid formatter for this entity.', max_length=50, prefix='publication_', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField()),
                ('doi', models.URLField()),
                ('date', models.DateField()),
                ('authors', models.CharField()),
                ('journal', models.CharField()),
                ('volume', models.CharField()),
                ('issue', models.CharField()),
                ('pages', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='posttag_', primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='post_', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField()),
                ('subtitle', models.CharField()),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.project')),
                ('publication_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='posttag_', primary_key=True, serialize=False, unique=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag')),
            ],
        ),
    ]
