# Generated by Django 5.0.8 on 2024-09-04 20:20

import charidfield.fields
import django.core.validators
import django.db.models.deletion
import ksuid.ksuid
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='addr_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=50, null=True)),
                ('building_suite_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid US postal code in the format XXXXX or XXXXX-XXXX.', regex='^\\d{5}(?:-\\d{4})?$')])),
            ],
        ),
        migrations.CreateModel(
            name='AgroProcess',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='agroProcess_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('external_id', models.CharField(max_length=255)),
                ('external_reference', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='attr_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField()),
                ('abbreviation', models.CharField()),
                ('description', models.TextField()),
                ('domain', models.CharField(choices=[('trial', 'Trial'), ('project', 'Project'), ('germplasm', 'Germplasm')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AwsModel',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='awsModel_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('endpoint_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='commonName_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='image_', primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255, validators=[django.core.validators.validate_image_file_extension])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('creation_date_time', models.DateTimeField()),
                ('storage_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='loc_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('plot', 'Plot'), ('trial', 'Trial'), ('general', 'General')])),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='observation_', primary_key=True, serialize=False, unique=True)),
                ('date_time', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='proj_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField()),
                ('funding', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='state_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraitAttribute',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='traitAttr_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraitEntity',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='traitEntity_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='treatment_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('germplasm', 'Germplasm'), ('planting', 'Planting'), ('fertilizer', 'Fertilizer'), ('operations', 'Operations'), ('herbicide', 'Herbicide'), ('other', 'Other')], max_length=255)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='variable_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255, unique=True)),
                ('sop_url', models.URLField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('corn', 'Corn'), ('soybean', 'Soybean'), ('pgc grass', 'PGC Grass'), ('pgc clover', 'PGC Clover'), ('weed', 'Weed'), ('soil', 'Soil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarMethod',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='varMethod_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarScale',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='varScale_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Germplasm',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='germ_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('pgc', 'PGC'), ('crop', 'Crop')], max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(default='spp.', max_length=255)),
                ('common_name_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.commonname')),
            ],
        ),
        migrations.CreateModel(
            name='GermplasmAlias',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='germAlias_', primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=255)),
                ('germplasm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.germplasm')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOperation',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='imageOperation_', primary_key=True, serialize=False, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('in progress', 'In Progress'), ('failure', 'Failure')], max_length=50)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.image')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.awsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='observation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.observation'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='org_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('abbreviation', models.CharField(unique=True)),
                ('ror_id', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid ROR ID in the format https://ror.org/XXXXXXXXX.', regex='^https://ror\\.org/[a-zA-Z0-9]{9}$')])),
                ('address_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data_storage.address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='person_', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=1)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('affiliation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.organization')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.person'),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='plot_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('main plot', 'Main Plot'), ('split plot', 'Split Plot'), ('split split plot', 'Split Split Plot'), ('split split split plot', 'Split Split Split Plot')])),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.CharField(blank=True, max_length=10, null=True)),
                ('column', models.CharField(blank=True, max_length=10, null=True)),
                ('width_m', models.DecimalField(decimal_places=4, help_text='The width of the plot object in meters.', max_digits=10)),
                ('length_m', models.DecimalField(decimal_places=4, help_text='The length of the plot object in meters.', max_digits=10)),
                ('location_id', models.ForeignKey(blank=True, limit_choices_to={'type': 'plot'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_storage.location')),
                ('parent_plot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_storage.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotCrop',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='plotCrop_', primary_key=True, serialize=False, unique=True)),
                ('plot_year', models.CharField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2024, max_length=4)),
                ('germplasm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.germplasm')),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.plot')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='plot_crop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.plotcrop'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.state'),
        ),
        migrations.CreateModel(
            name='TreatmentLevel',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='treatmentLevel_', primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(max_length=255)),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='PlotTreatment',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='plotTreatment_', primary_key=True, serialize=False, unique=True)),
                ('plot_crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.plotcrop')),
                ('treatment_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.treatmentlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trial_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('establishment_year', models.CharField(choices=[(1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2024, max_length=4)),
                ('multi_year', models.BooleanField(default=False)),
                ('affiliation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.organization')),
                ('location_id', models.ForeignKey(limit_choices_to={'type': 'trial'}, on_delete=django.db.models.deletion.CASCADE, to='data_storage.location')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.person')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.project')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='trial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='data_storage.trial'),
        ),
        migrations.CreateModel(
            name='TrialAttribute',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialAttr_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialEvent',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialEvent_', primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('comment', models.TextField(max_length=500)),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.agroprocess')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialTreatment',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialTreatment_', primary_key=True, serialize=False, unique=True)),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.treatment')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialYear',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialYear_', primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2024)),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='variable_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.variable', to_field='label'),
        ),
        migrations.AddField(
            model_name='variable',
            name='method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.varmethod'),
        ),
        migrations.AddField(
            model_name='variable',
            name='scale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.varscale'),
        ),
        migrations.CreateModel(
            name='VarTrait',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='varTrait_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('external_ontology_reference', models.URLField(blank=True, null=True)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.traitattribute')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.traitentity')),
            ],
        ),
        migrations.AddField(
            model_name='variable',
            name='trait_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.vartrait'),
        ),
        migrations.AddConstraint(
            model_name='germplasmalias',
            constraint=models.UniqueConstraint(fields=('germplasm_id', 'alias'), name='germplasm_alias_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='plotcrop',
            constraint=models.UniqueConstraint(fields=('plot_id', 'germplasm_id', 'plot_year'), name='plot_crop_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='treatmentlevel',
            constraint=models.UniqueConstraint(fields=('treatment_id', 'level'), name='treatment_level_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('trial_id', 'label'), name='plot_trial_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='trialtreatment',
            constraint=models.UniqueConstraint(fields=('trial_id', 'treatment_id'), name='trial_treatment_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='trialyear',
            constraint=models.UniqueConstraint(fields=('trial_id', 'year'), name='trial_year_composite_key'),
        ),
    ]
