# Generated by Django 5.0.8 on 2024-09-06 20:56

import charidfield.fields
import django.db.models.deletion
import ksuid.ksuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ontology', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='commonName_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='treatment_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('germplasm', 'Germplasm'), ('planting', 'Planting'), ('fertilizer', 'Fertilizer'), ('operations', 'Operations'), ('herbicide', 'Herbicide'), ('other', 'Other')], max_length=255)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Germplasm',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='germ_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('pgc', 'PGC'), ('crop', 'Crop')], max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(default='spp.', max_length=255)),
                ('common_name_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.commonname')),
            ],
        ),
        migrations.CreateModel(
            name='GermplasmAlias',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='germAlias_', primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=255)),
                ('germplasm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.germplasm')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='plot_', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('main plot', 'Main Plot'), ('split plot', 'Split Plot'), ('split split plot', 'Split Split Plot'), ('split split split plot', 'Split Split Split Plot')])),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.CharField(blank=True, max_length=10, null=True)),
                ('column', models.CharField(blank=True, max_length=10, null=True)),
                ('width_m', models.DecimalField(decimal_places=4, help_text='The width of the plot object in meters.', max_digits=10)),
                ('length_m', models.DecimalField(decimal_places=4, help_text='The length of the plot object in meters.', max_digits=10)),
                ('location_id', models.ForeignKey(blank=True, limit_choices_to={'type': 'plot'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.location')),
                ('parent_plot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_storage.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotCrop',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='plotCrop_', primary_key=True, serialize=False, unique=True)),
                ('plot_year', models.CharField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2024, max_length=4)),
                ('germplasm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.germplasm')),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='observation_', primary_key=True, serialize=False, unique=True)),
                ('date_time', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('observer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.person')),
                ('variable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.variable', to_field='label')),
                ('plot_crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.plotcrop')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentLevel',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='treatmentLevel_', primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(max_length=255)),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='PlotTreatment',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='plotTreatment_', primary_key=True, serialize=False, unique=True)),
                ('plot_crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.plotcrop')),
                ('treatment_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.treatmentlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trial_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('establishment_year', models.CharField(choices=[(1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2024, max_length=4)),
                ('multi_year', models.BooleanField(default=False)),
                ('affiliation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.organization')),
                ('location_id', models.ForeignKey(limit_choices_to={'type': 'trial'}, on_delete=django.db.models.deletion.CASCADE, to='resources.location')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.person')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.project')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='trial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='data_storage.trial'),
        ),
        migrations.CreateModel(
            name='TrialAttribute',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialAttr_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialEvent',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialEvent_', primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('comment', models.TextField(max_length=500)),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.agroprocess')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialTreatment',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialTreatment_', primary_key=True, serialize=False, unique=True)),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.treatment')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialYear',
            fields=[
                ('db_id', charidfield.fields.CharIDField(default=ksuid.ksuid.Ksuid, editable=False, help_text='ksuid formatter for this entity.', max_length=50, prefix='trialYear_', primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2024)),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.trial')),
            ],
        ),
        migrations.AddConstraint(
            model_name='germplasmalias',
            constraint=models.UniqueConstraint(fields=('germplasm_id', 'alias'), name='germplasm_alias_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='plotcrop',
            constraint=models.UniqueConstraint(fields=('plot_id', 'germplasm_id', 'plot_year'), name='plot_crop_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='treatmentlevel',
            constraint=models.UniqueConstraint(fields=('treatment_id', 'level'), name='treatment_level_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('trial_id', 'label'), name='plot_trial_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='trialtreatment',
            constraint=models.UniqueConstraint(fields=('trial_id', 'treatment_id'), name='trial_treatment_composite_key'),
        ),
        migrations.AddConstraint(
            model_name='trialyear',
            constraint=models.UniqueConstraint(fields=('trial_id', 'year'), name='trial_year_composite_key'),
        ),
    ]
